### ISSUE TITLE
Does not process files with spaces or special characters on Mac. 

### ISSUE THREAD

**Issue by juan9999** [hvdwolf/jExifToolGUI#279] opened 2022-12-25 07:02 UTC
**Version (please complete the following information):**
 - OS: [MacOS]
 - Version [l13
 - Package [macos bundle]

**Describe the bug**
1. If I have a file called a filename with many spaces.jpg

And I try to run an ExifTool Command (say -exif:all=)

I get
Error: File not found - /Users/bernie/Library/CloudStorage/Dropbox/a
Error: File not found - filename
Error: File not found - with
Error: File not found - many
Error: File not found - spaces.jpg
    0 image files updated
    5 files weren't updated due to errors

2. Is there a way to chain exif commands (remove all exif, add a copywrite notice)

3. Is there another way to delete all exif info from a file without manually loading commands?
 
4. Also is there a way to edit PNG Parameters tag?

**To Reproduce**
See above.

**Comment by mrtngrsbch** [comment] 2022-12-26 01:37
There are solutions for everything you are looking for, but I recommend to refer to the ExifTool documentation [https://exiftool.org/examples.html].

**Comment by hvdwolf** [comment] 2022-12-26 19:17
1. Is indeed a bug. Paths/Files containing spaces should be dealt with correctly.
2.  No, not via the application. And I have not foreseen such functionality in the future.
3. Yes, of course. That is part of jExifToolGUI (menu: Metadata -> Remove Metadata). But obviously you run into troubles with paths/files containing spaces. That should not happen and I have to check that. 
4.  I do not understand what you mean. PNG is fully supported via exiftool, both the exif data as well as the png textual data. If you need very specific tags you need to create a custom metadataset combination (menu: Tools)

**Comment by juan9999** [comment] 2022-12-26 19:42
Thanks for the prompt reply!
1. A fix would be awesome. I think special characters may not work either but my names contain both (/bin/sh: -c: line 0: syntax error near unexpected token `(')
2. So it's not possible to so something like this? or a | and save it as a favorite?
<img width="210" alt="Screenshot 2022-12-26 at 1 38 54 PM" src="https://user-images.githubusercontent.com/31065728/209579088-bbf59728-b67f-4985-bde1-335d03ea6c07.png">
3. Ah, I see it now. Having it as a icon on the preview pane would be awesome too! 
<img width="189" alt="Screenshot 2022-12-26 at 1 37 06 PM" src="https://user-images.githubusercontent.com/31065728/209578897-eb3e7395-684a-46e0-8d94-2030546a57c0.png">
4. the PNG parameter tag used in a lot of AI, is visible when I view the file, but is not editable in the "Edit data" tab.
<img width="520" alt="Screenshot 2022-12-26 at 1 34 18 PM" src="https://user-images.githubusercontent.com/31065728/209579156-c98bcc10-afd0-4bd5-962f-1b8ab608282a.png">
<img width="646" alt="Screenshot 2022-12-26 at 1 34 35 PM" src="https://user-images.githubusercontent.com/31065728/209579216-1826008f-7c5b-4c46-b99f-e356fb227af2.png">

Again, thanks for all your efforts with this tool! It will rock once 1. is fixed!

**Comment by hvdwolf** [comment] 2022-12-27 07:43
1. is a duplicate of #245 . You obviously used the "exiftool commands" option. I fixed that a few weeks ago for Linux/MacOS, but can't get it to work for Windows, so that's why there still isn't a bug fix.  It does work in another section of the program, so I did not find yet what I am doing wrong.


2.  No, that is not possible.
3. I have no plans to do that. This has been requested before by other users for "their" preferred option. Secondly, as you might have noticed (or not ;) ): all those icons are "non-destructive" actions on images: load, view, compare, etc.
4.  I am still not completely satisfied of how the program works as it started from what I needed. Of course I understand that others have different wishes and requirements and that the tool obviously needs more flexibility. That is indeed why the user defined screens were added to make a start with this but last year my personal and "business" life changed and I don't have and don't want to spend much time on this anymore. I alsmost came to a full stop. Besides: that's why it is open source: so that others can add their functionality (and a few did).

So in general: I have (almost) no objection (at all) about desired functionalities, as I fully understand them, but I am not sure whether these will come fast in the future. I don't want to abandon "this project", but it will be on low priority.

**Comment by hvdwolf** [comment] 2022-12-27 08:30
Exiftool itself allows for multiple commands in one commandline. My tool does nothing more than providing an interface where you indeed can store your favorites.
You might simply try something like `-exif:all= -artist=me `

With regard to the PNG writable tags. Only the following tags are writable (as of 12.30. Did not check newer versions yet):
  ```
Artist Author Collection Comment Copyright CreateDate CreationTime
  Description Disclaimer Document Label Make ModDate Model ModifyDate
  PNGWarning PixelUnits PixelsPerUnitX PixelsPerUnitY Software Source TimeStamp
  Title URL
```

**Closed** 2023-03-18 15:44 UTC
Labels: Fixed
