### ISSUE TITLE
Can't load HEIC

### ISSUE THREAD

**Issue by ggbal** [hvdwolf/jExifToolGUI#118] opened 2021-05-10 07:31 UTC
jExitToolGUI version: 1.8.1
MacOS: 11.3.1

- Add a directory with many HEIC images. The UI shows loading image but nothing is loaded.
- Add a single HEIC image, the behavior is the same as above
- Add a jpg, the thumbnail is loaded. Then I add a single HEIC image. Now, though the thumbnail is not loaded, the metadata are loaded and the rest EXIF operations succeeded. 
- Add a jpg, the thumbnail is loaded. Then I add a directory with many HEIC images, the behavior is the same as above when I just added a HEIC after adding jpg.

**Comment by hvdwolf** [comment] 2021-05-10 20:08
Something is going wrong with the initialization (first time run). I will check.

**Comment by hvdwolf** [comment] 2021-05-24 08:17
Can you please share some of your heic images?
I can't reproduce it.

**Comment by ggbal** [comment] 2021-06-04 17:28
I did more test and found this. If the folder name has a space in it, e.g. "t 2", you will hit that problem. Can you try?

**Comment by hvdwolf** [comment] 2021-06-05 09:18
The problem is slightly deeper. I use the java replace() method to replace all spaces in paths. When using a shell based call (which is necessary for sips), only the first space is replaced.
Then you have the replaceAll() function which should be used with a "regex" (regular expression). I do not use a regex but still that one needs to be used on MacOS.
Strange.

Now it works with one space, but also with multiple spaces.
Fixed in the development tree right now.

**Closed as completed** 2021-10-23 11:53 UTC
Labels: bug, Fixed
