### ISSUE TITLE
New functionality: the right direction?

### ISSUE THREAD

**Issue by hvdwolf** [hvdwolf/jExifToolGUI#189] opened 2021-11-08 19:36 UTC
@mrtngrsbch @comradekingu @MetadataDeluxe @KovalevArtem

Hi,
I did not want to open the "Discussions" section yet on this github, so I now "abuse" an issue ticket for it.

I changed the working of the program. I also changed one of the help texts (source string `leftcheckboxbarhelp`. The
![Screenshot 2021-11-08 20 11 58](https://user-images.githubusercontent.com/4520361/140803200-a177e7e5-4982-4cce-8167-f8a3cfc08e8c.png) button, and also one of the program strings (source string `lp.loadmetadata` to "Load metadata in foreground")

Loading metadata can now be done in the background which speeds up image loading considerably. See explanation below of that help text.

## The meaning of the checkboxes
<br><ul><li>Create previews (default unchecked): This creates a thumbnail. (Slows down the loading of images.) JPG/RAW/TIF images from a modern camera have an embedded preview. (Loads relatively fast.) Scanned or older images might not have these embedded previews. Creating the preview will take longer than simply retrieving it. With more than 20~50 images it might get too slow for you.</li><li>Load metadata (default unchecked):<ul><li>Checked: For every image all metadata is loaded in the foreground. This slows down loading but gives you immedately a basic view to some important general metadata.</li><li>UnChecked: This will load all metadata in the background. This speeds up loading the images considerably, but the "Compare Images" and "Search Metadata" buttons will only get enabled after the bacground process is ready.</li></ul>The metadata is loaded anyway to enable the searching in metadata.</ul><br>Disabling both options only displays filenames, with a small preview in the bottom left for the first loaded image. After loading and clicking a filename, it will load the preview image in the bottom left, and the metadata into the right pane.

I want to release this in 1.10.0 coming weekend or so, and I just pushed some betas to [mega.nz](https://mega.nz/folder/UFlRhYCZ#LITpkOKT79CNWtmdwCG0bw).

**<hr><hr>**
But this is actually a start to a new thumbnail left panel that should replace the left icon/metadata table. Now only as popup-frame to first build the functionality and then apply it to the left pane of the program. The right pane will stay the same.
See below a short preview. Double-click to display full size. This was discussed earlier to have a grid of thumbnails, instead of the current layout with the left icon table.
Is this a good direction to move to?

https://user-images.githubusercontent.com/4520361/140802346-c0a5436e-6600-4b74-b33c-b58f94638749.mp4

**Comment by MetadataDeluxe** [comment] 2021-11-09 17:04
Hi @hvdwolf

These are great developments! Yes, ultimately moving towards a thumbnail grid in the left side table is a great idea and will make the application more desirable to a lot more people. Your demo is looks good. I can see having that on the left and using the app in full-screen mode to view a lot of thumbnails.

For the current updates to 1.9.0, these are good enhancements.
Loading metadata in the background does help. Here's  test I did:

46 jpegs from a camera (they all have embedded previews)
Load metadata in background = 1:42
Load metadata in foreground = 2:21

Performance is better, but 1:42 to load 46 images still seems slow. Perhaps this is as fast as ExifTool can work.

Other thoughts:

1. After the images have loaded, metadata from the first one is displayed in the large metadata table on the right, meaning it is the currently selected image. In this case, it would be better if the first image thumbnail were highlighted to indicate it is selected and make it clear which image the displayed metadata is for.
2. When loading a group of images, it would be better if the metadata table were reset (file values were blank) in the same way the thumbnail table "resets". Currently the metadata from the last selected image remains on display while new files are loading and, after completion, it is unclear when the metadata for the new image has loaded.

**Comment by MetadataDeluxe** [comment] 2021-11-10 16:50
I'm getting much slower load times than you.
| Version         | images + loading                                           | seconds|
|---------------|-------------------------------------------------|------|
| 1.10.0 beta   | 16 jpgs with metadata background loading | 39.4 |

It's possible the issue is with my images or my computer. I'm attaching my test jpgs so you can test them too. I'm on a Lenovo with and Intel Core i5, 8 GB RAM, running Windows 10.
When I run the ExifTool command line to extract thumbnails, it get them in a couple of seconds.

[gregs_thumnb_test.zip](https://github.com/hvdwolf/jExifToolGUI/files/7514483/gregs_thumnb_test.zip)

**Comment by mrtngrsbch** [comment] 2021-11-10 16:58
Hi,
I am very excited about this very important development. I agree with the initiative as with all the preceding comments.

I could only add one small feature:
When displaying the preview metadata, it would be interesting to be able to control the metadata displayed there.
I understand that this is a special feature, but maybe it can be done at some point or keep in the sandbox.

![image](https://user-images.githubusercontent.com/693328/141154407-6d7cb41a-4263-48b6-af3f-4dc9fac09901.png)

Regarding loading speed: This is very important to me since it is not uncommon for me to want to edit 1000 images !
My workflow often includes the creation of 200X200 thumbnails of images that can be 24MB each !
When you multiply this by 1000 it gives a figure impossible to use with any editor.
Simple example:
1. `# -path ch *.tif mogrify -resize 200x200 -path ch *.jpg` 
2. I edit the metadata
3. Export the metadata: `# exiftool -xmp -b CCA-LAN-02-028.tif > CCA-LAN-02-028.xmp` 4.
4. Import to the original images: `# exiftool -tagsfromfile CCA-LAN-02-028.xmp -xmp CCA-LAN-02-028.tif`.

Again: Congratulations on the progress in this regard

**Comment by MetadataDeluxe** [comment] 2021-11-10 17:06
> 1. I agree, but I tried that already earlier. This is an event driven "color change" either by mouse or keyboard selection, to highlight that. I can't simulate that event programmatically (at least: I have not found it yet).

In this case, it might be better to not display the metadata in the table - let the user select an image to display. The metadata table could display "Select an image to display metadata" to prompt the user.

**Comment by hvdwolf** [comment] 2021-11-10 17:43
Now with tifs without previews.

> I'm getting much slower load times than you.

You do not have my 1.10 beta ! I an the only lucky one :)

**Comment by hvdwolf** [comment] 2021-11-10 18:01
> > 1. I agree, but I tried that already earlier. This is an event driven "color change" either by mouse or keyboard selection, to highlight that. I can't simulate that event programmatically (at least: I have not found it yet).
> 
> In this case, it might be better to not display the metadata in the table - let the user select an image to display. The metadata table could display "Select an image to display metadata" to prompt the user.

That has been mentioned/asked before by another user, but that is exactly why the image name is above the metadata table so that you can see it immediately. But obviously that is not very very obvious (pun intended).
Anyway: I will keep it in mind or try to think of a better option. Keeping it empty is also an option of course.

**Comment by MetadataDeluxe** [comment] 2021-11-10 18:29
How about... if there is only one image, display the metadata in the table, if there are several images, leave it empty.

**Comment by MetadataDeluxe** [comment] 2021-11-10 18:31
I am using version 1.9.0.1-20211108 from [mega.nz](https://mega.nz/folder/UFlRhYCZ#LITpkOKT79CNWtmdwCG0bw)

**Comment by hvdwolf** [comment] 2021-11-10 19:19
> I am using version 1.9.0.1-20211108 from [mega.nz](https://mega.nz/folder/UFlRhYCZ#LITpkOKT79CNWtmdwCG0bw)

Too old. I started this Yesterday (9 Nov).
Currently something goes wrong on windows with previews. I need to fix that first. The command uses percentages. I think that goes wrong on Windows.
If I have fixed that, I will release a new beta like 20211110 or 20211111

>
>How about... if there is only one image, display the metadata in the table, if there are several images, leave it empty.
That might be a good option. I will build that.

**Comment by hvdwolf** [comment] 2021-11-11 15:02
>
>How about... if there is only one image, display the metadata in the table, if there are several images, leave it empty.

Just added that as well and put a 1.9.9 on [mega.nz](https://mega.nz/folder/UFlRhYCZ#LITpkOKT79CNWtmdwCG0bw). Of course the major topic is the faster loading.

Like mentioned earlier: big tiffs without preview but with an alpha channel, will never load quickly with this build, as java does not support that "nicely". I will see if I can check that. If I can I will create an icon (still containing the alphachannel), and then in the background: convert the big tif to jpg, and make a thumbnail of that jpg. This is possible but will take some time and I want to already share this build with you so that you can test it.
If OK, this will be the 1.10 release.

Then I will go for the image grid, which might be the first 2.0 version as it is a major functionality change (and a major change of coding, next to the current faster loading).

**Comment by MetadataDeluxe** [comment] 2021-11-11 17:29
>> How about... if there is only one image, display the metadata in the table, if there are several images, leave it empty.

>Just added that as well and put a 1.9.9 on mega.nz. Of course the major topic is the faster loading.

This works very well.

The image load times are significantly faster!  My test group of 16 jpgs with metadata background loading now only takes 16 seconds.

I think this build is ready to release. It has many improvements and is much easier to use. I would make a few suggestions to tuning some file and metadata loading behavior, but these could be considered for the 2.0 version.

Congratulations on this new build!

**Comment by hvdwolf** [comment] 2021-11-11 20:14
Thanks.

I now fixed the tiffs with alpha channel as well. Leading them twice through a buffered image conversion strips the alpha channel automatically. A bit slower, but still faster than the original loading. And with a 40~60 MB tiff file the repeated loading from cache is almost immediately.
I will do some further testing on Windows and Mac to check on regression bugs.

I also uploaded the builds with the improved tiff loading: 20211111_2 version on [mega.nz](https://mega.nz/folder/UFlRhYCZ#LITpkOKT79CNWtmdwCG0bw).

**Comment by hvdwolf** [comment] 2021-11-11 22:22
>
> I could only add one small feature:
> When displaying the preview metadata, it would be interesting to be able to control the metadata displayed there.

It is also on my ToDo list, but not so high. I'm a photographer and therefore interested in the current basic set.
Your are also an archivist and interested in other metadata. I do understand that.
It will come.
But if you first select one of your created custom sets (see image) and only then load your images, they will show on the right side your desired info. In a much wider table like screen.
![Screenshot 2021-11-11 23 20 30](https://user-images.githubusercontent.com/4520361/141377277-9499e7fe-5a13-4824-8a1b-2e63c6331739.png)

**Comment by mrtngrsbch** [comment] 2021-11-12 18:57
> > I could only add one small feature:
> > When displaying the preview metadata, it would be interesting to be able to control the metadata displayed there.
> 
> It is also on my ToDo list, but not so high. I'm a photographer and therefore interested in the current basic set. Your are also an archivist and interested in other metadata. I do understand that. It will come. But if you first select one of your created custom sets (see image) and only then load your images, they will show on the right side your desired info. In a much wider table like screen. ![Screenshot 2021-11-11 23 20 30](https://user-images.githubusercontent.com/4520361/141377277-9499e7fe-5a13-4824-8a1b-2e63c6331739.png)

Yes Harry, I use it and it is very comfortable. I like it that way. And I'm very happy with JTG's progress 🔥.
My comment was just a minor feature.

Our colleague @MetadataDeluxe is helping me a lot with VRA Core which is great, although very complex as a whole.
I dream of the day when we can create the panels for VRA like the 'Customizable Metadata Export-Import Plugin for Adobe Bridge' plugin: https://github.com/MetadataDeluxe/adobe_bridge_custom_export-import

**Comment by mrtngrsbch** [comment] 2021-11-17 14:39
Hi,

I like having two preview modes 🔥
I find several issues. Excuse me for sending them all together 

My firewall detects an outbound IP... 
![image](https://user-images.githubusercontent.com/693328/142218791-5e2b9e2a-7ab8-4bd0-a30b-fa5ba5f00dc5.png)

A JPG image has no file name
![image](https://user-images.githubusercontent.com/693328/142219526-f263120e-902a-4c01-a163-4361a83db209.png)

Compare images does not seem to work
![image](https://user-images.githubusercontent.com/693328/142220061-cc399e78-692d-4230-8603-0595be7213c0.png)

In MacOS you cannot see more than two preview columns.
![image](https://user-images.githubusercontent.com/693328/142220405-6a551e46-de01-43ec-93b0-b1b050ad4505.png)

**Comment by KovalevArtem** [comment] 2021-11-17 14:49
On Windows there is no problem with preview columns ...
![image](https://user-images.githubusercontent.com/36500228/142222563-9d855d4c-89f8-4b4a-8b94-a46d2445a6b3.png)
![image](https://user-images.githubusercontent.com/36500228/142222616-52dfb88d-d5c4-4408-bf3f-a91653068671.png)

**Comment by mrtngrsbch** [comment] 2021-11-17 14:50
now, after restarting... other things happen
1. the image WITHOUT filename now shows it
2. but the same image has no thumnbail (??)

![image](https://user-images.githubusercontent.com/693328/142222368-4984cf25-b3fd-4c1c-90f8-e37d522ea6d7.png)

https://user-images.githubusercontent.com/693328/142223159-0a67994b-a631-4e36-ad1a-a7a0a3fe680b.mp4

**Comment by mrtngrsbch** [comment] 2021-11-17 15:28
ops...
my previous version 1.10.0
also has problems to see the previews. I didn't notice that

![image](https://user-images.githubusercontent.com/693328/142229677-fc7edab3-783c-4ec8-8f5d-4163813b9059.png)

**Comment by hvdwolf** [comment] 2021-11-17 17:39
@mrtngrsbch 
* The ip-address: JTG only(!) connects to github to check the version on startup and notifies the user in case of an update available. No other connections are made apart from user initiated actions to open a website or so.
* The image without name and then being black: All embedded thumbnails are 160x120, or 120x160. That is the industry standard, so I also make a thumbnail of largest side 160 in case the image doesn't contain a thumbnail. That thumbnail being shown is much bigger, and then it turns black. It is also square, which means that width and height are the same (seemingly). _Please share the image with me._
* the black thumbnail from a jpg: This is really strange. _Please share the image with me._
* Compare images not working: indeed, this is a bug. already fixed (but not uploaded yet). I had to change a lot of functions. Forgot this one (and maybe more?)
* Only 2 columns for the grid:  This is some weird shortcoming. Please first drag either the right edge of the application wider, or the left edge. Then you can probably drag the "divider" more to left or right (my old 2009 macbook has low resolution. I do not even have the screen space to do so.)


And in general: For some reason I am not yet able to wipe the grid before loading a new image set.

**Comment by mrtngrsbch** [comment] 2021-11-17 18:31
@hvdwolf 

The 2 black images have NOT been modified and previously I could see them well.
![IMG_9173-Molinos-de-viento](https://user-images.githubusercontent.com/693328/142259327-548c541a-6ad1-46e3-a566-e67ca1232a6a.jpg)
![vrae_exiftool_example](https://user-images.githubusercontent.com/693328/142259346-f3dfcc0b-fc5f-4d39-bf79-99765f6fb26d.jpg)

2 columns = yes !
that was the problem ;-)
my screen hace 2560 px !



https://user-images.githubusercontent.com/693328/142260730-ee364d14-c947-44d5-aaa1-09b148071f3b.mp4

**Comment by MetadataDeluxe** [comment] 2021-11-17 20:30
First of all, congratulations on the thumbnail grid, I really like it.

- the black thumbnail from a jpg: I am seeing this too. In my case, I'm sure the jpgs do not have embedded previews. I think they were downloaded from another source, so I don't know the details of how they were produced.

![image](https://user-images.githubusercontent.com/5862936/142277188-8e55b22c-da36-42b9-95d8-ece158d84cb4.png
![01376401](https://user-images.githubusercontent.com/5862936/142277246-7764ad0d-3172-4958-9ddc-d87f180dd6a6.jpg)
)

**Comment by hvdwolf** [comment] 2021-11-18 07:20
> 
> 2 columns = yes ! that was the problem ;-) my screen have 2560 px !

The right panel has a minimum width to accomodate the table. That is why you can't drag the divider more to the right than the minimum width of the right table, and why you either need to drag the left window border to the left or the right window border to the right.

**Comment by hvdwolf** [comment] 2021-11-18 11:24
With regard to the black images. Normally the exif byte order in jpegs is "litle endian". These images are all "big endian" encoded. I do not know yet if that is the issue, but can you please check for your jpgs?
![Screenshot 2021-11-18 12 16 39](https://user-images.githubusercontent.com/4520361/142405616-36c3e0a6-9df2-4bfe-bd42-0786b3549599.png)

I am now running through my collection to check if I can find same images and whether this really is the issue, but so far all my jpg images are little endian. Same for png, tiff and RAW (when applicable for the RAW type)

**Comment by MetadataDeluxe** [comment] 2021-11-18 16:36
Both of these files are Big-endian.

![image](https://user-images.githubusercontent.com/5862936/142455573-35bd019d-4b0d-4e1a-a8c2-6f3962e3690a.png)

![image](https://user-images.githubusercontent.com/5862936/142455718-f248c313-2a4a-4c43-827a-59f459dceaa4.png)

![Basic_EM_Mural](https://user-images.githubusercontent.com/5862936/142456944-5d27238b-aab3-4f4a-b82f-3255ab8b2d7c.jpg)
![Basic_EM_Performance](https://user-images.githubusercontent.com/5862936/142456946-c7346c97-6b3f-44cc-8cb9-4b9c76e0c28e.jpg)

**Comment by MetadataDeluxe** [comment] 2021-11-18 16:53
I just noticed another problem: file names with Chinese characters cannot be read. 

![image](https://user-images.githubusercontent.com/5862936/142459796-26ad010b-c086-47d2-a404-aa2656b1e74a.png)

I am on Windows, which might be more problematic for character encoding than a Mac.
I found information on file names in the ExifTool documentation. It still seems like a tricky problem.

"ExifTool 9.79 and later allow the file name encoding to be specified with -charset filename=CHARSET, where CHARSET is the name of a valid ExifTool character set, preferably UTF8"
https://exiftool.org/exiftool_pod.html

**Comment by mrtngrsbch** [comment] 2021-11-18 17:29
> With regard to the black images. Normally the exif byte order in jpegs is "litle endian". These images are all "big endian" encoded. I do not know yet if that is the issue, but can you please check for your jpgs? !

Indeed !
Those two images are 'Big-endian'.
File | Exif Byte Order | Big-endian (Motorola, MM)


PS: I love this team of nerds... I didn't know there were big and little Indians.

**Comment by mrtngrsbch** [comment] 2021-11-18 17:32
> Both of these files are Big-endian.

hey...
I just found another great Indian, but this one looks good.

![ScreenShot 2021-11-18 a las 14 31 07](https://user-images.githubusercontent.com/693328/142466708-6d240d58-c3c6-46f9-b9d0-005e39189185.jpg)

**Comment by hvdwolf** [comment] 2021-11-18 18:20
I finally found images with big endian encoding. 9 out of 10 work fine, but some not.
At that time I was working on a Mac in iPhoto. But that still might not be the issue as most do display correctly.
On the other hand: not one single little-endian is displaying as black.

>
> I just noticed another problem: file names with Chinese characters cannot be read.

I dealt with the utf- characterset heavily in the previous release where we were discussing about multi-byte characters. Those were the russian chanracters, but for Chinese or Korean is the same. But at that time I was only looking at metadata inside the image. I did not even think of file names. 
I will have a look at that now. But I guess it will be diffucly as well.

**Comment by hvdwolf** [comment] 2021-11-20 10:27
When available, I extract the thumbnail form the images as this is by far the fastest method. These are always 1620x120 (by definition from some international camera & image committee). The below thumbnail is a non-standard photoshop thumbnail of 256x256. And that is the same reason why the file name doesn't show up: my grid is 180x180 to show this 160x120 images including their filename. This one simply doesn't fit.
I used to have a "non-standard icon resize" function, but I lost it in the entire "fast loading and grid display" conversion. Will build that back.
![142259327-548c541a-6ad1-46e3-a566-e67ca1232a6a_PhotoshopThumbnail](https://user-images.githubusercontent.com/4520361/142722546-682074ad-7ff0-48cb-aa0c-8e6bf320adeb.jpg)

But I still haven't found the reason why those images go black. I have now gone through (really) thousands of images and only experience it for a few, not all, big endian images. I shortly thought it had to do with 'Y Cb Cr Subsampling" being "YCbCr4:4:4 (1 1)", but upon checking this all the others did function. Now searching if it is the combination of big-endian and  this subsampling (but if so: no idea how to handle that)

**Comment by hvdwolf** [comment] 2021-11-20 12:43
>
>I just noticed another problem: file names with Chinese characters cannot be read.
> I am on Windows, which might be more problematic for character encoding than a Mac.
>I found information on file names in the ExifTool documentation. It still seems like a tricky problem.

>"ExifTool 9.79 and later allow the file name encoding to be specified with -charset filename=CHARSET, where CHARSET is the >name of a valid ExifTool character set, preferably UTF8"
>https://exiftool.org/exiftool_pod.html

The above is for the metadata, which is by default ansi/ascii for exif and iptc, but which can be overruled. I did spend a lot of time into that for the Russian characters and the like. (xmp is by default utf-8)
Secondly: There are 2 different UTF-8 file handlings. The file handling itself which is already UTF-8 and internal commandline and internal (metadata) file encoding: The latter was were I spend a lot of time.

What you now encounter is probably not UTF-8 (2-byte characters), but UTF-16 (3-byte characters) encoding. If I experiment with Cyrillic and Greek and the like, it works fine, but not with Chinese. I renamed some files using random chinese texts. They display correct in my terminal and filemanager, but not in JTG.
Somehow my system is displaying it correctly, but my java program is not.

The clipname in the grid is incorrect. The path/name (in bold) above the metadata is correct as it is HTML encoded, but the image file name in the metadata is again incorrect.
![utf8-encoded](https://user-images.githubusercontent.com/4520361/142726596-33a44ff0-b4ec-42a3-94a0-dbcf72e78d6d.png)

But if now also HTML-encode my filenames before display and my metadata before display, I get:
![html-encoded](https://user-images.githubusercontent.com/4520361/142726620-771512a7-5e78-4997-ab4a-8302dad48540.png)

I will have to change a lot of fields and output though.  I will let you know when I have a new build.


One thing I can't change until now is the file dialog itself. It still displays incorrect.
![Screenshot 2021-11-20 13 26 28](https://user-images.githubusercontent.com/4520361/142726283-1754f610-393d-4d38-9578-e36c55742eb5.png)

**Comment by mrtngrsbch** [comment] 2021-11-23 01:38
> When available, I extract the thumbnail form the images as this is by far the fastest method. These are always 160x120 (by definition from some international camera & image committee). The below thumbnail is a non-standard photoshop thumbnail of 256x256. And that is the same reason why the file name doesn't show up: my grid is 180x180 to show this 160x120 images including their filename. This one simply doesn't fit. I used to have a "resize a non-standard thumbnail" function, but I lost it in the entire "fast loading and grid display" conversion. Will build that back. ![142259327-548c541a-6ad1-46e3-a566-e67ca1232a6a_PhotoshopThumbnail](https://user-images.githubusercontent.com/4520361/142722546-682074ad-7ff0-48cb-aa0c-8e6bf320adeb.jpg)
> 
> But I still haven't found the reason why those images go black. I have now gone through (really) thousands of images and only experience it for a few, not all, big endian images. I shortly thought it had to do with 'Y Cb Cr Subsampling" being "YCbCr4:4:4 (1 1)", but upon checking this all the others did function. Now searching if it is the combination of big-endian and this subsampling (but if so: no idea how to handle that)

I just did an export to JPG (JPG > JPG) from MacOS Preview and a correct thumbnail was created = now it looks good.

so this is now fixed

![image](https://user-images.githubusercontent.com/693328/142959458-db6017c1-8469-488b-8368-9ecd0cb07707.png)

**Comment by hvdwolf** [comment] 2021-11-23 07:52
> 
> I just did an export to JPG (JPG > JPG) from MacOS Preview and a correct thumbnail was created = now it looks good.
> 
> so this is now fixed
> 
Thanks for being nice 😉 , but this is not a fix, but a workaround.
I still have no idea though about the black previews.

**Comment by mrtngrsbch** [comment] 2021-11-23 16:09
> > I just did an export to JPG (JPG > JPG) from MacOS Preview and a correct thumbnail was created = now it looks good.
> > so this is now fixed
> 
> Thanks for being nice 😉 , but this is not a fix, but a workaround. I still have no idea though about the black previews.

No... of course this is not an 'elegant' solution, but I also understand that it is very expensive to solve all the problems of all the platforms... and also problems derived from other applications.
🐽

**Comment by hvdwolf** [comment] 2021-11-28 16:47
Hi all,
I also worked on the background reading of metadata. It is now 3-25 times faster depending on the number of files. With about 65 files it is about 7X faster. With more than 330 times it is almost 17X faster (my experience that is with jpegs)

Changes so far:
* Improve reading of metadata in background with factor 3-15 (depending on number of images)
* Screen output from a lot of names and metadata is now HTML-encoded. jExifToolGUI now correctly displays in UTF-8 (2-byte character encoding), also on Windows, but most platforms are not yet UTF-16 (3-byte character encoding) ready unless specifically installed, which means that Chinese and/or Taiwanese texts are not correctly displayed. HTML encoding overcomes this.
* On image loading display some "placeholder" texts in the grid and the metadata table, to show the user that the program is really doing something.
* Improve exiftool startup and preferences check. It contained a small error but it is also amazing what users manage to select as "exiftool".
* Fix error in search/display of metadata via search button. Errors or corruptions in metadata made JTG crash in the background.

on [mega.nz](https://mega.nz/folder/ZIMSiBIa#G3fbbuPwkNYFNmKdp8s9fQ) as 1.11.1 beta (will become the 2.0).

Not solved yet
* black images
* Display of metadata of images with Chinese (or Korean or Taiwanese) characters in the filename

**Comment by mrtngrsbch** [comment] 2021-11-30 16:09
Diff 1.10.0 vs 1.11.1

- rare crop thumb
- big endian
- opening 63 images (890MB) = can't see the difference in metadata load (harry, could you tell me how do you measure the loading speed?)

https://user-images.githubusercontent.com/693328/144083463-82fda3c9-45e1-45de-8f8b-1acadb3a75c8.mp4

**Comment by MetadataDeluxe** [comment] 2021-12-01 19:29
I'm seeing that the background metadata loading is much faster in 1.11.1 (image loading is the same). This is great. Previously the metadata load indicator would spin for a very long time, making me wonder if it was really doing something or was just stuck. Nice improvement.

The placeholder text is also a good addition.

**Comment by hvdwolf** [comment] 2021-12-02 18:40
I used to read the metadata picture per picture meaning that for every picture an exiftool call was done.
Now I create a very long command line reading all metadata in one go and I rewrote the parsing of these entire bulk of data.

@mrtngrsbch : I checked on my macbook, but I get with the collections I use there also 2-5X faster performance.
I use a stopwatch for measuring. I watch the notification in the bottom right. When it switches from "loading images" to "loading metadata ...", I start the stopwatch and stop when the message is removed (= ready loading)

**Comment by mrtngrsbch** [comment] 2021-12-02 20:21
@hvdwolf : hehe... I love analog technology ;-)
I've done the same calculation but I found it very inaccurate. Maybe I should do it with many more images, but it's true that 'it's faster';
if it comes to it, the current speed is very satisfactory for me, I don't see it as a problem.

**Comment by mrtngrsbch** [comment] 2021-12-05 05:30
Hi @hvdwolf 

A very strange event has happened.
A few days ago I made a copy with MacOS Preview and it looked fine.
https://github.com/hvdwolf/jExifToolGUI/issues/189#issuecomment-976092447

Today I open JTG (in versions 1.10.0 and 11.11.1) and again I see the black image !
Then I created a third image [IMG_9173-Windmills3.jpg] and this one looks fine.... 
ALL Big-Endian

![image](https://user-images.githubusercontent.com/693328/144734904-c4cc4339-3bd3-474b-b3d5-f29261665fb1.png)

I think I can now confirm that it is JTG that is creating this problem.

**Comment by hvdwolf** [comment] 2021-12-05 11:03
> 
> I think I can now confirm that it is JTG that is creating this problem.
>

I fully agree that JTG is the problem. Last week I already found already that the java JPEGwriter contains an error when converting PNGs with alpha-channel to JPG, and that it will generate a black image in such circumstances. But in this case we start from jpegs without alpha channel. I already tried that same png workaround (you never know), but it doesn't fix it.

I am trying to find out WHY it is happening. Which images do cause this? So far in all my experiments only Big Endian encoded images have this, like mentioned earlier, but by far not all. I used to have an HP camera which did create Big Endian jpeg images, but all those images work fine. Why?
I am trying to find the WHY,  so I might be able to write something to fix that.

**Comment by hvdwolf** [comment] 2021-12-05 11:36
I just found one thing in "corrupt" metadata for the earlier delivered images.
![image](https://user-images.githubusercontent.com/4520361/144744668-e453792f-ede6-4747-bae3-ea81445c1549.png)

```
exiftool -validate -warning -a *.jpg
======== fix1.jpg
Validate                        : 7 Warnings (2 minor)
Warning                         : [minor] Non-standard IFD0 tag 0x000b ProcessingSoftware
Warning                         : [minor] IPTC Country-PrimaryLocationCode too short (2 bytes; should be 3)
Warning                         : Missing required JPEG ExifIFD tag 0x9101 ComponentsConfiguration
Warning                         : Missing required JPEG ExifIFD tag 0xa000 FlashpixVersion
Warning                         : Missing required JPEG ExifIFD tag 0xa002 ExifImageWidth
Warning                         : Missing required JPEG ExifIFD tag 0xa003 ExifImageHeight
Warning                         : Missing required JPEG IFD0 tag 0x0213 YCbCrPositioning
======== fix2.jpg
Validate                        : 9 Warnings (1 minor)
Warning                         : [minor] Non-standard IFD0 tag 0x000b ProcessingSoftware
Warning                         : Missing required JPEG ExifIFD tag 0x9101 ComponentsConfiguration
Warning                         : Missing required JPEG ExifIFD tag 0xa000 FlashpixVersion
Warning                         : Missing required JPEG ExifIFD tag 0xa002 ExifImageWidth
Warning                         : Missing required JPEG ExifIFD tag 0xa003 ExifImageHeight
Warning                         : Missing required JPEG IFD0 tag 0x011a XResolution
Warning                         : Missing required JPEG IFD0 tag 0x011b YResolution
Warning                         : Missing required JPEG IFD0 tag 0x0128 ResolutionUnit
Warning                         : Missing required JPEG IFD0 tag 0x0213 YCbCrPositioning
======== fix3.jpg
Validate                        : 4 Warnings
Warning                         : Missing required JPEG ExifIFD tag 0x9101 ComponentsConfiguration
Warning                         : Missing required JPEG ExifIFD tag 0xa000 FlashpixVersion
Warning                         : Missing required JPEG ExifIFD tag 0xa002 ExifImageWidth
Warning                         : Missing required JPEG ExifIFD tag 0xa003 ExifImageHeight
    3 image files read

```
You see already that I copied and renamed them because I wanted to fix the metadata where possible using
`exiftool -preserve -overwrite_original -all= -tagsfromfile @ -all:all -unsafe -F *.jpg`
And it did correct part of the metadata, but it didn't fix the black thumbnail issue. 
It is going wrong on the saving of the thumbnail. The thumbnail is displayed correctly at first. Upon reloading, means loading the created thumb, you get the black image.

**Comment by hvdwolf** [comment] 2021-12-05 15:05
And finally I think I have fixed the black images. I created a new 1.11.2 on [mega.nz](https://mega.nz/folder/QMFQiBwY#g1edTuICxcGWHBoIQnHzwg).
I now first create a new 2nd "BufferedImage" from the original image being resized to a java "ImageIcon" via BufferedImage (so step 1), and then write that 2nd BufferedImage to the cache folder forcing it to "BufferedImage.TYPE_INT_RGB". The resize from full-size (4~80MB)  to thumbnail is the "time consuming" step, but the second conversion from thumbnail to thumbnail (max 160x160 at 3~15 Kbyte in memory) is not even noticable.

Thumbnails are written to `<home folder>/jexiftoolgui_data/cache/`. The images are simply called `<imagename>_ThumbnailImage.jpg` for both embedded thumbnails and my created thumbnails, and they are called `<imagename>_PhotoshopThumbnail.jpg` when coming from a photoshop embedded image.

Please delete the black image thumbnails (or simply empty your cache folder), and please try again.
That means initial loading to create the thumbnail, and then reloading to see whether the saved thumbnail is now correct.

I will also add some functionality to completely wipe the cache folder, and something like: "wipe older than: 3 months, 6 months, when over xy MB"
I have now 528 thumbnails totalling 4.6 MB. With all the tests I had something like 2000 thumbnails around 18~19 MB. Not really very much, but some users might want to keep it "neat and tidy".

**Comment by mrtngrsbch** [comment] 2021-12-05 21:27
Coool
I cleared the cache and now all the images look fine again!
I'm sorry that this solution was so expensive.

I find the solution to clear the cache interesting, eventually all applications do something similar. Notion.so has a function to erase everything and restart (original restore), when something goes wrong.

**Closed** 2022-01-23 12:25 UTC
Labels: enhancement
